# Generated by Django 4.1.7 on 2023-04-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_entregable_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregable',
            old_name='fechaDeEntrega',
            new_name='fecha_De_Entrega',
        ),
    ]
